pipeline {
 agent any
   stages{
     stage('Build'){
        steps {
         dir('cicd-pipeline-train-schedule-pipelines') {
            echo 'Running build automation'
            sh './gradlew build --no-daemon'
            archiveArtifacts artifacts: 'dist/trainSchedule.zip'
         }
       }     
     }
   }
}
